=== languagetool-org/languagetool/languagetool-core/src/main/resources/org/languagetool/rules/false-friends.dtd
<!--
False Friends DTD
Daniel Naber (http://www.danielnaber.de), 2001-12-21, 2005-08-20

This DTD defines a format for "false friends".

The DTD is designed in a way so that false friends can be
used in both ways, e.g. 'actual' is a false friend for
speakers of German, and 'aktuell' is a false friend for
speakers of English who write a text in German. The file
is not limited to English/German but can actually be 
extended to any number of languages, hopefully with minimal
redundancy.
FIXME: replace DTD with XSD to have full power of rules here: we cannot really
add any exceptions...
-->

<!ENTITY % Languages "(en|en-GB|de|fr|es|pl|sv|gl|ca|it|da|nl|ru|ja|pt|ga)">

<!ELEMENT rules (rulegroup)+>
<!ELEMENT rulegroup (rule+)>
<!ATTLIST rulegroup id ID #REQUIRED>
<!-- Whether the rule is switched by default off -->
<!ATTLIST rulegroup default (off|on) #IMPLIED>

<!ELEMENT rule (pattern, translation+, example*)>
<!-- Whether the rule is switched by default off -->
<!ATTLIST rule default (off|on) #IMPLIED>

<!ELEMENT pattern (token)*>
<!ATTLIST pattern lang %Languages; #REQUIRED>

<!ELEMENT token (#PCDATA)*>
<!-- is token a lemma? -->
<!ATTLIST token inflected (yes|no) "no">
<!-- is it a regexp? -->
<!ATTLIST token regexp (yes|no) "no">
<!-- is it negated? - instead of ^ in 0.8.2 -->
<!ATTLIST token negate (yes|no) "no">
<!-- POS tag -->
<!ATTLIST token postag CDATA #IMPLIED>
<!ATTLIST token postag_regexp (yes|no) "no">
<!ATTLIST token negate_pos (yes|no) "no">
<!ATTLIST token postag_exceptions CDATA #IMPLIED>
<!-- number of tags to skip before the match is found -->
<!ATTLIST token skip CDATA #IMPLIED>
<!-- Spaces are important for matching, leave them alone: -->
<!ATTLIST token
 xml:space (preserve) #FIXED 'preserve'>

<!ELEMENT translation (#PCDATA)>
<!ATTLIST translation lang %Languages; #REQUIRED>

<!ELEMENT example (#PCDATA)>
<!ATTLIST example type (correct|incorrect) #REQUIRED>
<!-- Spaces are important for testing suggestions, leave them alone: -->
<!ATTLIST example
 xml:space (preserve) #FIXED 'preserve'>

=== languagetool-org/languagetool/trunk/JLanguageTool/src/rules/false-friends.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE rules SYSTEM "false-friends.dtd">
<?xml-stylesheet type="text/xsl" href="print-ff.xsl" 
title="Pretty print" ?>
<?xml-stylesheet type="text/css" href="false-friends.css" 
title="Easy editing stylesheet" ?>
<!--
Rules: False Friends
Copyright (C) 2001-2005 Daniel Naber (http://www.danielnaber.de)
$Id: false-friends.xml,v 1.18 2007-10-12 13:15:22 milek_pl Exp $
TODO: berate = beschimpfen
-->
<rules>
  <rulegroup id="ABSURD">
    <rule>
      <pattern lang="en">
        <token>an</token>
        <token>absurd</token>
      </pattern>
      <translation lang="pl">absurdalny</translation>
      <example type="correct">This is an absurd suggestion!</example>
    </rule>
    <rule>
      <pattern lang="pl">
        <token>absurd</token>
      </pattern>
      <translation lang="en">absurdity</translation>
      <example type="correct">To absurd!</example>
    </rule>
  </rulegroup>
  <rulegroup id="ALSO">
    <rule>
      <pattern lang="en">
        <token>also</token>
      </pattern>
      <translation lang="de">auch</translation>
      <example type="correct">Did he also work at that company?</example>
    </rule>
    <rule>
      <pattern lang="de">
        <token>also</token>
      </pattern>
      <translation lang="en">thus</translation>
      <translation lang="en">therefore</translation>
      <translation lang="en">so</translation>
      <example type="correct">Also haben wir uns für die Alternative entschieden.</example>
    </rule>
  </rulegroup>
  <rulegroup id="ACTUAL">
    <rule>
      <pattern lang="en">
        <token regexp="yes">actual|actually</token>
      </pattern>
      <translation lang="de">eigentlich</translation>
      <translation lang="pl">rzeczywisty</translation>
      <translation lang="fr">vrai</translation>
      <translation lang="fr">effectif</translation>
    </rule>
    <rule>
      <pattern lang="de">
        <token>aktuell</token>
      </pattern>
      <translation lang="en">current</translation>
      <translation lang="en">(the) latest</translation>
      <translation lang="en">up-to-date</translation>
    </rule>
    <rule default="off">
      <pattern lang="pl">
        <token inflected="yes">aktualny</token>
      </pattern>
      <translation lang="en">current</translation>
      <translation lang="en">(the) latest</translation>
      <translation lang="en">up-to-date</translation>
    </rule>
  </rulegroup>
  <rulegroup id="ACTUALIZED">
    <rule>
      <pattern lang="en">
        <token regexp="yes">actualised|actualized</token>
      </pattern>
      <translation lang="de">verwirklicht</translation>
      <translation lang="pl">urzeczywistniony</translation>
      <translation lang="pl">urzeczywistniony</translation>
    </rule>
    <rule>
      <pattern lang="de">
        <token>aktualisiert</token>
      </pattern>
      <translation lang="en">updated</translation>
    </rule>
    <rule>
      <pattern lang="pl">
        <token inflected="yes" postag="ppas.*" postag_regexp="yes">zaktualizować</token>
      </pattern>
      <translation lang="en">updated</translation>
    </rule>
  </rulegroup>
  <rulegroup id="ACTUALIZE">
    <rule>
      <pattern lang="en">
        <token regexp="yes">actualise|actualize</token>
      </pattern>
      <translation lang="de">verwirklichen</translation>
      <translation lang="de">realistisch darstellen</translation>
    </rule>
    <rule>
      <pattern lang="de">
        <token inflected="yes">aktualisieren</token>
      </pattern>
      <translation lang="en">update</translation>
    </rule>
  </rulegroup>
  <rulegroup id="ADEPT">
    <rule>
      <pattern lang="en">
        <token>adept</token>
      </pattern>
      <translation lang="pl">biegły</translation>
      <translation lang="pl">mistrz</translation>
      <translation lang="fr">expert</translation>
      <translation lang="es">experto</translation>
      <translation lang="es">hábil</translation>
    </rule>
    <rule>
      <pattern lang="pl">
        <token inflected="yes">adept</token>
      </pattern>
      <translation lang="en">follower</translation>
      <translation lang="en">admirer</translation>
    </rule>
    <rule>
      <pattern lang="fr">
        <token inflected="yes">adepte</token>
      </pattern>
      <translation lang="en">follower</translation>
      <translation lang="en">admirer</translation>
    </rule>
    <rule>
      <pattern lang="es">
        <token inflected="yes">adepto</token>
      </pattern>
      <translation lang="en">follower</translation>
      <translation lang="en">admirer</translation>
    </rule>
  </rulegroup>
  <rulegroup id="ADVOCATE">
    <rule>
      <pattern lang="en">
        <token>advocate</token>
      </pattern>
      <translation lang="de">Befürworter</translation>
      <translation lang="pl">rzecznik</translation>
    </rule>
    <rule>
      <pattern lang="de">
        <token>Advokat</token>
      </pattern>
      <translation lang="en">attorney</translation>
      <translation lang="en">lawyer</translation>
    </rule>
    <rule>
      <pattern lang="pl">
        <token inflected="yes">adwokat</token>
      </pattern>
      <translation lang="en">attorney</translation>
      <translation lang="en">lawyer</translation>
    </rule>
  </rulegroup>
  <rulegroup id="AFFAIR">
    <rule>
      <pattern lang="en">
        <token inflected="yes">affair</token>
      </pattern>
      <translation lang="pl">sprawa</translation>
      <translation lang="pl">romans</translation>
    </rule>
    <rule>
      <pattern lang="pl">
        <token inflected="yes">afera</token>
      </pattern>
      <translation lang="en">scandal</translation>
      <translation lang="en">fuss</translation>
    </rule>
  </rulegroup>
  <rulegroup id="ANTICS">
    <rule>
      <pattern lang="en">
        <token>antics</token>
      </pattern>
      <translation lang="pl">błazeństwa</translation>
      <translation lang="pl">wyskoki</translation>
    </rule>
    <rule>
      <pattern lang="pl">
        <token>antyki</token>
      </pattern>
      <translation lang="en">antiques</translation>
    </rule>
  </rulegroup>
  <rulegroup id="APARTMENT">
    <rule>
      <pattern lang="en">
        <token>apartment</token>
      </pattern>
      <translation lang="pl">mieszkanie</translation>
    </rule>
    <rule>
      <pattern lang="pl">
        <token inflected="yes" postag="subst:sg:.*" postag_regexp="yes">apartament</token>
      </pattern>
      <translation lang="en">suite (in a hotel)</translation>
      <translation lang="en">luxury apartment</translation>
    </rule>
  </rulegroup>
  <rulegroup id="ARGUMENT">
    <rule>
      <pattern lang="en">
        <token>argument</token>
      </pattern>
      <translation lang="de">Streit</translation>
    </rule>
    <rule>
      <pattern lang="de">
        <token>Argument</token>
      </pattern>
      <translation lang="en">point</translation>
      <translation lang="en">reasoned argument</translation>
    </rule>
  </rulegroup>
  <rulegroup id="ART">
    <rule>
      <pattern lang="en">
        <token>art</token>
      </pattern>
      <translation lang="de">Kunst</translation>
    </rule>
    <rule>
      <pattern lang="de">
        <token>Art</token>
      </pattern>
      <translation lang="en">kind</translation>
      <translation lang="en">manner</translation>
      <translation lang="en">way</translation>
      <translation lang="en">type</translation>
    </rule>
  </rulegroup>
  <rulegroup id="AUDITION">
    <rule>
      <pattern lang="en">
        <token>audition</token>
      </pattern>
      <translation lang="pl">przesłuchanie (do roli)</translation>
    </rule>
    <rule>
      <pattern lang="pl">
        <token inflected="yes">audycja</token>
      </pattern>
      <translation lang="en">broadcast</translation>
      <translation lang="en">program</translation>
    </rule>
  </rulegroup>
  <rulegroup id="BALD">
    <rule>
      <pattern lang="en">
        <token>bald</token>
      </pattern>
      <translation lang="de">glatzköpfig</translation>
      <translation lang="de">kahl</translation>
    </rule>
    <rule>
      <pattern lang="de">
        <token>bald</token>
      </pattern>
      <translation lang="en">soon</translation>
    </rule>
  </rulegroup>
  <rulegroup id="BARRACKS">
    <rule>
      <pattern lang="en">
        <token>barracks</token>
      </pattern>
      <translation lang="pl">koszary</translation>
    </rule>
    <rule>
      <pattern lang="pl">
        <token inflected="yes">barak</token>
      </pattern>
      <translation lang="en">shed</translation>
      <translation lang="en">bull pen</translation>
    </rule>
  </rulegroup>
  <rulegroup id="BATON">
    <rule>
      <pattern lang="en">
        <token>baton</token>
      </pattern>
      <translation lang="pl">pałeczka</translation>
      <translation lang="pl">batuta</translation>
    </rule>
    <rule>
      <pattern lang="pl">
        <token inflected="yes">baton</token>
      </pattern>
      <translation lang="en">bar (e.g., chocolate bar)</translation>
    </rule>
  </rulegroup>
  <rulegroup id="BECOME">
    <rule>
      <pattern lang="en">
        <token inflected="yes">become</token>
      </pattern>
      <translation lang="de">werden</translation>
    </rule>
    <rule>
      <pattern lang="de">
        <token inflected="yes">bekommen</token>
      </pattern>
      <translation lang="en">to get</translation>
      <translation lang="en">receive</translation>
    </rule>
  </rulegroup>
  <rulegroup id="BERATE">
    <rule>
      <pattern lang="en">
        <token inflected="yes">berate</token>
      </pattern>
      <translation lang="de">beschimpfen</translation>
    </rule>
    <rule>
      <pattern lang="de">
        <token inflected="yes">beraten</token>
      </pattern>
      <translation lang="en">to provide advice</translation>
      <translation lang="en">to give advice</translation>
    </rule>
  </rulegroup>
  <rulegroup id="BILLION">
