=== languagetool-org/languagetool/languagetool-core/src/main/resources/org/languagetool/rules/rules.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<!-- 
 * LanguageTool, a natural language style checker 
 * Copyright (c) Marcin MiÅ‚kowski, 2014 (http://www.languagetool.org)
 * 
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301
 * USA
 
 Schema for rule files
 -->

	<xs:include schemaLocation="pattern.xsd"/>

	<xs:annotation>
		<xs:documentation xml:lang="en">Main element</xs:documentation>
	</xs:annotation>

	<xs:element name="rules">
		<xs:complexType>
			<xs:choice minOccurs="1" maxOccurs="unbounded" >
				<xs:element ref="unification" />
				<xs:element ref="phrases"/>
				<xs:element ref="category"/>
			</xs:choice>
			<xs:attribute name="lang" type="xs:language" use="required" />
			<xs:attribute name="idprefix" type="xs:string" use="optional" />
			<xs:attribute name="integrate" use="optional">
			<xs:simpleType>
				<xs:restriction base="xs:NMTOKEN">
					<xs:enumeration value="replace"/>
					<xs:enumeration value="add"/>
				</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:annotation>
		<xs:documentation xml:lang="en">Use the category element to group rules/rulegroups.</xs:documentation>
		<xs:documentation xml:lang="en">The attribute name shows the category use, e.g. 'Grammar', 'Spelling', 'Style' etc.</xs:documentation>
	</xs:annotation>

	<xs:element name="category">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element ref="rule" />
				<xs:element ref="rulegroup" />
			</xs:choice>
			<xs:attribute name="default" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="off" />
						<xs:enumeration value="on" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute ref="name" use="required" />
			<xs:attribute name="id" type="xs:ID" use="required" />
			<xs:attribute ref="type" use="optional" />
			<xs:attribute name="external" type="binaryYesNo" use="optional" />
			<xs:attribute name="tab" use="optional" />
			<xs:attribute name="tags" use="optional" />
		</xs:complexType>
	</xs:element>

	<xs:annotation>
		<xs:documentation xml:lang="en"> Defines a group of rules
			to display several rules as one in the configuration user interface. A group has a unique ID.
			The whole rule group can be switched by default off using the attribute 'default'.</xs:documentation>
	</xs:annotation>
	<xs:element name="rulegroup">
		<xs:complexType>
			<xs:sequence minOccurs="1">
				<xs:element ref="url" minOccurs="0" maxOccurs="1" />
				<xs:element ref="short" minOccurs="0" maxOccurs="1" />
				<xs:element ref="antipattern" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="rule" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="default" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="off" />
						<xs:enumeration value="temp_off" />
						<xs:enumeration value="on" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute ref="name" use="required" />
			<xs:attribute name="id" type="xs:ID" use="required" />
			<xs:attribute ref="type" use="optional" />
			<xs:attribute name="tags" use="optional" />
		</xs:complexType>
	</xs:element>

	<xs:attribute name="type">
		<xs:annotation>
			<xs:documentation xml:lang="en">
				Localization Quality Issue Type, according to Internationalization Tag Set (ITS) Version 2.0,
				see http://www.w3.org/International/multilingualweb/lt/drafts/its20/its20.html#lqissue-typevalues
				(added in LanguageTool 2.0)
			</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:NMTOKEN">
				<xs:enumeration value="terminology" />
				<xs:enumeration value="mistranslation" />
				<xs:enumeration value="omission" />
				<xs:enumeration value="untranslated" />
				<xs:enumeration value="addition" />
				<xs:enumeration value="duplication" />
				<xs:enumeration value="inconsistency" />
				<xs:enumeration value="grammar" />
				<xs:enumeration value="legal" />
				<xs:enumeration value="register" />
				<xs:enumeration value="locale-specific-content" />
				<xs:enumeration value="locale-violation" />
				<xs:enumeration value="style" />
				<xs:enumeration value="characters" />
				<xs:enumeration value="misspelling" />
				<xs:enumeration value="typographical" />
				<xs:enumeration value="formatting" />
				<xs:enumeration value="inconsistent-entities" />
				<xs:enumeration value="numbers" />
				<xs:enumeration value="markup" />
				<xs:enumeration value="pattern-problem" />
				<xs:enumeration value="whitespace" />
				<xs:enumeration value="internationalization" />
				<xs:enumeration value="length" />
				<xs:enumeration value="non-conformance" />
				<xs:enumeration value="uncategorized" />
				<xs:enumeration value="other" />
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>

	<xs:annotation>
		<xs:documentation xml:lang="en"> The rule element. The
			unique ID is required only if the rule is not contained in a rule group.
			The rule can be switched by default off (using the default attribute).
		</xs:documentation>
	</xs:annotation>
	<xs:element name="rule">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="antipattern" minOccurs="0" maxOccurs="unbounded"/>
				<xs:choice>
					<xs:element ref="pattern" />
					<xs:element ref="regexp" />
				</xs:choice>
				<xs:element ref="filter" minOccurs="0" maxOccurs="1" />
				<xs:element ref="message" />
				<xs:element ref="suggestion" minOccurs="0" maxOccurs="15" />
				<xs:element ref="url" minOccurs="0" maxOccurs="1" />
				<xs:element ref="short" minOccurs="0" />
				<xs:element ref="example" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="default" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="off" />
						<xs:enumeration value="temp_off" />
						<xs:enumeration value="on" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="name" type="xs:string" use="optional" />
			<xs:attribute name="id" type="xs:ID" use="optional" />
			<xs:attribute ref="type" use="optional" />
			<xs:attribute name="tags" use="optional" />
		</xs:complexType>
	</xs:element>

 	<xs:element name="pattern">
		<xs:complexType>
			<xs:choice minOccurs="1" maxOccurs="unbounded">
				<xs:element ref="token" />
				<xs:element ref="phraseref" />
				<xs:element ref="and" />
				<xs:element ref="or" />
				<xs:element ref="unify" />
				<xs:element ref="marker" maxOccurs="1"/>
			</xs:choice>
			<xs:attribute name="case_sensitive" type="binaryYesNo" use="optional" />
			<xs:attribute name="raw_pos" type="binaryYesNo" use="optional" />
		</xs:complexType>
	</xs:element>

	<xs:element name="regexp">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="case_sensitive" type="binaryYesNo" use="optional"/>
                    <xs:attribute name="type" use="optional" default="smart">
                        <xs:simpleType>
                            <xs:restriction base="xs:NMTOKEN">
                                <xs:enumeration value="smart" />
                                <xs:enumeration value="exact" />
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                    <xs:attribute name="mark" use="optional">
                        <xs:simpleType>
							<xs:restriction base="xs:integer">
								<xs:minInclusive value="1" />
							</xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:annotation>
		<xs:documentation xml:lang="en">A negative-matching pattern used to
			mark up complex exceptions in rules. Note: it does not support
			phrases and OR operations for simplicity.
		</xs:documentation>
	</xs:annotation>
	<xs:element name="antipattern">
		<xs:complexType>
			<xs:choice minOccurs="1" maxOccurs="unbounded">
				<xs:element ref="token" />
				<xs:element ref="and" />
				<xs:element ref="unify" />
				<xs:element ref="marker" />
			</xs:choice>
			<xs:attribute name="case_sensitive" type="binaryYesNo" use="optional" />
		</xs:complexType>
	</xs:element>

	<xs:annotation>
		<xs:documentation xml:lang="en">A short description of
			the error detected by this rule displayed on the
			context menu in LibreOffice/OpenOffice.org.</xs:documentation>
	</xs:annotation>
	<xs:element name="short" type="xs:token" />


	<xs:annotation>
		<xs:documentation xml:lang="en">Message shown to the user if a rule matches.</xs:documentation>
	</xs:annotation>
	<xs:element name="message" xml:space="preserve">
		<xs:complexType mixed="true">
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="suggestion" />
				<xs:element ref="match" />
			</xs:choice>
		    <xs:attribute name="suppress_misspelled" type="binaryYesNo" use="optional"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="filter">
		<xs:complexType>
			<xs:attribute name="class" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation xml:lang="en">A fully qualified Java class that extends the RuleFilter class</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="args" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation xml:lang="en">Arguments given to the Java code: a space-separated list with 
						elements in the form of 'key:\x', where key is the parameter name and x is a number
						that refers to the pattern's token. Number and parameter names depend on the Java code.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:annotation>
			<xs:documentation xml:lang="en">URL with further information
				about the linguistic rule behind this error.</xs:documentation>
  	</xs:annotation>
	<xs:element name="url" type="xs:anyURI" />

	<xs:annotation>
		<xs:documentation xml:lang="en">Suggestion displayed to the user.</xs:documentation>
	</xs:annotation>
	<xs:element name="suggestion">
		<xs:complexType mixed="true">
			<xs:sequence minOccurs='0' maxOccurs='unbounded'>
				<xs:element ref="match" />
			</xs:sequence>
			<xs:attribute name="suppress_misspelled" type="binaryYesNo" use="optional"/>
		</xs:complexType>
	</xs:element>

	<xs:annotation>
		<xs:documentation xml:lang="en">Specifies examples used
			in JUnit tests and as documentation.
			The attribute 'correction' is used to check if the suggested correction
			is correct; multiple suggestions are joined with "|".
			The attribute triggers_error is not used by the software.
		</xs:documentation>
	</xs:annotation>

	<xs:element name="example" xml:space="preserve">
	<xs:complexType mixed="true">
	  <xs:choice minOccurs="0" maxOccurs="unbounded">
		<xs:element name="marker" >
			<xs:complexType>
				<xs:simpleContent>
					<xs:extension base="xs:string"/>
				</xs:simpleContent>
			</xs:complexType>
		</xs:element>
	  </xs:choice>
	  <xs:attribute name="correction" type="xs:string" use="optional" />
		<xs:attribute name="type" use="optional">
		<xs:simpleType>
		  <xs:restriction base="xs:NMTOKEN">
			<xs:enumeration value="correct" />
			<xs:enumeration value="incorrect" />
			<xs:enumeration value="triggers_error" />
		  </xs:restriction>
		</xs:simpleType>
		</xs:attribute>
	<xs:attribute name="reason" type="xs:string" use="optional" />
	</xs:complexType>
  </xs:element>

    <xs:attribute name="name">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:minLength value="1"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>

</xs:schema>

=== languagetool-org/languagetool/languagetool-language-modules/sr/src/main/resources/org/languagetool/rules/sr/grammar-logical.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../../../../../../../../../languagetool-core/src/main/resources/org/languagetool/rules/print.xsl" ?>
<?xml-stylesheet type="text/css" href="../../../../../../../../../languagetool-core/src/main/resources/org/languagetool/rules/rules.css"
        title="Easy editing stylesheet" ?>

<!-- Serbian Grammar and Typo Rules for LanguageTool See tagset.txt for the
	meaning of the POS tags Copyright (C) 2001-2015 Daniel Naber (http://www.danielnaber.de),
	Marcin Miłkowski and the LanguageTool contributors Portions of rules are
	converted from After The Deadline grammar checker, available at http://open.afterthedeadline.com/,
	licensed under GNU GPL. This library is free software; you can redistribute
	it and/or modify it under the terms of the GNU Lesser General Public License
	as published by the Free Software Foundation; either version 2.1 of the License,
	or (at your option) any later version. This library is distributed in the
	hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
	warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
	GNU Lesser General Public License for more details. You should have received
	a copy of the GNU Lesser General Public License along with this library;
	if not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth
	Floor, Boston, MA 02110-1301 USA -->

<!DOCTYPE rules [
        <!ENTITY weekdays "понедељак|уторак|среда|четвртак|петак|субота|недеља">
        <!ENTITY abbrevWeekdays "пон?|Tue?|Wed?|Thu?|Fri?|Sat?|Sun?">
        <!ENTITY months "јануар|фебруар|март|април|мај|јун|јул|август|септембар|октобар|новембар|децембар|јануара|фебруара|марта|априла|маја|јуна|јула|августа|септембра|октобра|новембра|децембра">
        <!ENTITY abbrevMonths "јан|феб|мар|апр|мај|јун|јул|авг|сеп|окт|нов|дец">
        <!ENTITY double_num "два|три|четири|2|3|4">
        ]>

<rules lang="sr" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="../../../../../../../../../languagetool-core/src/main/resources/org/languagetool/rules/rules.xsd">

    <category id="SR_LOGIC" name="Логичке грешке">

        <rulegroup id="INVALID_DATE" name="Непостојећи датум, на пример „31. фебруар 2014“">
            <rule>
                <pattern>
                    <!-- "31. јуна 2014 г." -->
                    <token>31</token>
                    <token>.</token>
                    <token regexp="yes">апр(ил(а)?)?|јун(а)?|сеп(темб(ар|ра))?|нов(емб(ар|ра))?</token>
                </pattern>
                <message>У овом месецу има само 30 дана.</message>
                <example correction="">То се догодило <marker>31. новембра</marker> 2014.</example>
                <example>То се догодило <marker>30. новембра</marker>2014. г.</example>
            </rule>
            <rule>
                <pattern>
                    <token>31</token>
                    <token>.</token>
                    <token regexp="yes">0?4|0?6|0?9|11</token>
                    <token>.</token>
                </pattern>
                <message>Овај месец има само 30 дана.</message>
                <example correction="">То је било <marker>31.4.</marker>2014.</example>
                <example correction="">То је било <marker>31.04.</marker>.</example>
                <example correction="">То је било <marker>31.11.</marker>.</example>
                <example>То је било <marker>30.11.</marker>.</example>
                <example>То је било <marker>30.10.</marker>.</example>
            </rule>
            <rule>
                <regexp>3[01]\. феб(руар(а)?)?</regexp>
                <message>Фебруар има само 28 дана (односно 29 ако је година преступна).</message>
                <example correction="">То је било <marker>31. фебруара</marker>.</example>
                <example correction="">То је било <marker>30. фебруара</marker>.</example>
                <example>То је било <marker>28. фебруара</marker>.</example>
            </rule>
            <rule>
                <regexp>3[01]\. ?0?2\.</regexp>
                <message>Фебруар има само 28 дана (односно 29 ако је година преступна).</message>
                <example correction="">То је било <marker>31.02.</marker>.</example>
                <example correction="">То је било <marker>31.2.</marker>.</example>
                <example>То је било <marker>28.2.</marker>.</example>
                <example>То је било <marker>28.02.</marker>.</example>
            </rule>
            <rule>
                <regexp>(3[2-9]|[4-9]\d)\. ?(\d\d?|&abbrevMonths;)\. ?\d\d\d\d</regexp>
                <message>У овом датуму дан је погрешан.</message>
                <example correction="">То је било <marker>32.8.2014</marker>.</example>
                <example correction="">То је било <marker>55.8.2014</marker>.</example>
                <example correction="">То је било <marker>32. авг. 2014</marker>.</example>
                <example>То је било <marker>30.8.2014</marker>.</example>
            </rule>
            <rule>
                <regexp>(3[2-9]|[4-9]\d)\. (&months;) \d\d\d\d</regexp>
                <message>У овом датуму дан је погрешан.</message>
                <example correction="">То је било <marker>32. августа 2014</marker>.</example>
                <example>То је било <marker>30. августа 2014</marker>.</example>
            </rule>
            <rule>
                <regexp>\d\d?\.(1[3-9]|[2-9]\d)\.\d\d\d\d</regexp>
                <message>У овом датуму месец је погрешан.</message>
                <example correction="">То је било <marker>11.13.2014</marker>.</example>
                <example correction="">То је било <marker>11.20.2014</marker>.</example>
                <example>То је било <marker>11.12.2014</marker>.</example>
            </rule>
            <rule>
                <pattern>
                    <token>29</token>
                    <token>.</token>
                    <token regexp="yes">2|02|фебр?</token>
                    <token>.</token>
                    <token regexp="yes">\d\d(00|\d[13579]|[02468][26]|[13579][048])
                        <exception regexp="yes">[13579][26]00|[2468][048]00</exception>
                    </token>
                </pattern>
                <message>Фебруар \5 нема 29 дана зато што то није преступна година.</message>
                <url>https://sr.wikipedia.org/wiki/Преступна_година</url>
                <!-- 1900 is not a leap year (divisible by 100) -->
                <example correction="">Дана <marker>29. феб. 1900</marker>.</example>
                <example correction="">Дана <marker>29.02.1900</marker>.</example>
                <example correction="">Дана <marker>29.2.1900</marker>.</example>
                <!-- 2000 is a leap year (divisible by 400) -->
                <example>Дана <marker>29.2.2000</marker>.</example>
                <example correction="">Дана <marker>29.2.2001</marker>.</example>
                <example correction="">Дана <marker>29.2.2002</marker>.</example>
                <example correction="">Дана <marker>29.2.2003</marker>.</example>
                <!-- 2004 is a leap year (divisible by 4) -->
                <example>Дана <marker>29.2.2004</marker>.</example>
                <example correction="">Дана <marker>29.2.2005</marker>.</example>
                <example correction="">Дана <marker>29.2.2006</marker>.</example>
                <example correction="">Дана <marker>29.2.2007</marker>.</example>
                <!-- 2008 is a leap year (divisible by 4) -->
                <example>Дана <marker>29.2.2008</marker>.</example>
                <example correction="">Дана <marker>29.2.2009</marker>.</example>
                <example correction="">Дана <marker>29.2.2010</marker>.</example>
                <example correction="">Дана <marker>29.2.2011</marker>.</example>
                <!-- 2012 is a leap year (divisible by 4) -->
                <example>Дана <marker>29.2.2012</marker>.</example>
                <example correction="">Дана <marker>29.2.2014</marker>.</example>
                <example>Дана <marker>29.2.2016</marker>.</example>
                <example correction="">Дана <marker>29.2.2018</marker>.</example>
                <example>Дана <marker>29.2.2020</marker>.</example>
                <!-- 2100 is not a leap year (divisible by 100) -->
                <example correction="">Дана <marker>29.2.2100</marker>.</example>
            </rule>
            <rule>
                <pattern>
                    <token>29</token>
                    <token>.</token>
                    <token regexp="yes">фебруар(а)?</token>
                    <token regexp="yes">\d\d(00|\d[13579]|[02468][26]|[13579][048])
                        <exception regexp="yes">[13579][26]00|[2468][048]00</exception>
                    </token>
                </pattern>
                <message>Фебруар \4 нема 29 дана зато што то није преступна година.</message>
                <url>https://sr.wikipedia.org/wiki/Преступна_година</url>
                <example>Дана <marker>29. фебруара 2012</marker>.</example>
                <example correction="">Дана <marker>29. фебруара 2014</marker>.</example>
            </rule>
        </rulegroup> <!-- id="INVALID_DATE" -->

        <rule id="YEAR_20001" name="„Maj 20001 (Маj 2001)“">
            <pattern>
                <token regexp="yes">&months;|годин(а|е)</token>
                <token regexp="yes">200\d\d</token>
            </pattern>
            <message>Заиста \2? Или је <suggestion><match no="1" /> <match no="2" regexp_match="200" regexp_replace="20" /></suggestion>?</message>
            <short>Грешка писања?</short>
            <example correction="маја 2014">Планирао сам распуст <marker>маја 20014</marker>.</example>
        </rule>
    </category> <!-- id="LOGIC" name="Логичке грешке" -->
</rules>

=== languagetool-org/languagetool/languagetool-language-modules/tl/src/main/resources/org/languagetool/rules/tl/grammar.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../../../../../../../../../languagetool-core/src/main/resources/org/languagetool/rules/print.xsl" ?>
<?xml-stylesheet type="text/css" href="../../../../../../../../../languagetool-core/src/main/resources/org/languagetool/rules/rules.css" title="Easy editing stylesheet" ?>
<!--
Tagalog Grammar and Typo Rules for LanguageTool
Copyright (C) 2011 Nathaniel Oco and Allan Borra (http://www.dlsu.edu.ph/research/centers/adric/nlp/)

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA

See tagset.txt for the different POS, Lexical Categories, and corresponding attributes
-->
<rules lang="tl" xsi:noNamespaceSchemaLocation="../../../../../../../../../languagetool-core/src/main/resources/org/languagetool/rules/rules.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <category id="PROPER_ALA_ALAS_USAGE" name="Proper usage of Gitling (-)">
        <rule id="ALA_MISSING_GITLING" name="Gitling for 'ala-una'">
			<pattern case_sensitive="no">
				<token>ala</token>
				<token regexp="yes">una|1</token>
			</pattern>
			<message>Did you mean to add a gitling? Use <suggestion>ala-\2</suggestion>.</message>
			<short>Use a gitling between "ala" and "una". "Ala" is used only for "una".</short>
			<example correction="ala-una" type="incorrect"><marker>ala una</marker></example>
			<example correction="ala-1" type="incorrect"><marker>ala 1</marker></example>
			<example type="correct"><marker>ala-una"</marker></example>
			<example type="correct"><marker>ala-1"</marker></example>
		</rule>
        <rule id="ALAS_MISSING_GITLING" name="Gitling for 'alas-(dos->dose)'">
            <pattern case_sensitive="no">
                <token>alas</token>
                <token regexp="yes">(1[0-2]|[2-9]|dos|tres|kwatro|singko|sais|siete|otso|nwebe|dyes|onse|dose)</token>
            </pattern>
            <message>Did you mean to add a gitling? Use <suggestion>alas-\2</suggestion>.</message>
            <short>Use a gitling between "alas" and time values between 2-12.</short>
            <example correction="alas-dos" type="incorrect"><marker>alas dos</marker></example>
			<example correction="alas-2" type="incorrect"><marker>alas 2</marker></example>
			<example type="correct"><marker>alas-dos</marker></example>
			<example type="correct"><marker>alas-2</marker></example>
        </rule>
		<rule id="ALA_INCORRECT_USAGE" name="Incorrect Usage for 'ala'">
			<pattern case_sensitive="no">
				<token>ala</token>
				<token>-</token>
                <token regexp="yes">(1[0-2]|[2-9]|dos|tres|kwatro|singko|sais|siete|otso|nwebe|dyes|onse|dose)</token>
			</pattern>
  			<message>Did you mean to use <suggestion>alas-\3</suggestion>?</message>
			<short>Use alas-(2-12 / dos-dose) instead of ala-(2-12 / dos-dose).</short>
			<example correction="alas-dos" type="incorrect"><marker>ala-dos</marker></example>
			<example correction="alas-2" type="incorrect"><marker>ala-2</marker></example>
			<example type="correct"><marker>alas-dos</marker></example>
			<example type="correct"><marker>alas-2</marker></example>
		</rule>
		<rule id="ALAS_INCORRECT_USAGE" name="Incorrect Usage for 'alas'">
			<pattern case_sensitive="no">
				<token>alas</token>
				<token>-</token>
				<token regexp="yes">una|1</token>
			</pattern>
  			<message>Did you mean to use <suggestion>ala-\3</suggestion>?</message>
			<short>Use ala-una instead of alas-una.</short>
			<example correction="ala-una" type="incorrect"><marker>alas-una</marker></example>
			<example correction="ala-1" type="incorrect"><marker>alas-1</marker></example>
			<example type="correct"><marker>ala-una</marker></example>
			<example type="correct"><marker>ala-1</marker></example>
		</rule>
    </category>
</rules>

=== languagetool-org/languagetool/trunk/JLanguageTool/src/rules/cs/grammar.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="../print.xsl" title="Pretty print" ?>
<?xml-stylesheet type="text/css" href="../rules.css" title="Easy editing stylesheet" ?>
<!--
A demo rule file for LanguageTool
Copyright (C) 2005 Daniel Naber (http://www.danielnaber.de)

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA

$Id$
-->

<rules lang="cs" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../rules.xsd">

  <category name="misc">

    <!-- a trivialdemo rule that matches "foo" followed by "bar" -->
    <rule id="DEMO_RULE" name="Find 'foo bar'">
      <pattern case_sensitive="no">
        <token>foo</token>
        <token>bar</token>
      </pattern>
      <message>Did you mean <suggestion>fuu bah</suggestion>?</message>
      <example type="correct">This is <marker>fuu bah</marker>.</example>
      <example type="incorrect">This is <marker>foo bar</marker>.</example>
    </rule>

  </category>

</rules>
