=== languagetool-org/languagetool/languagetool-core/src/main/resources/org/languagetool/rules/rules.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<!-- 
 * LanguageTool, a natural language style checker 
 * Copyright (c) Marcin MiÅ‚kowski, 2014 (http://www.languagetool.org)
 * 
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301
 * USA
 
 Schema for rule files
 -->

	<xs:include schemaLocation="pattern.xsd"/>

	<xs:annotation>
		<xs:documentation xml:lang="en">Main element</xs:documentation>
	</xs:annotation>

	<xs:element name="rules">
		<xs:complexType>
			<xs:choice minOccurs="1" maxOccurs="unbounded" >
				<xs:element ref="unification" />
				<xs:element ref="phrases"/>
				<xs:element ref="category"/>
			</xs:choice>
			<xs:attribute name="lang" type="xs:language" use="required" />
			<xs:attribute name="idprefix" type="xs:string" use="optional" />
			<xs:attribute name="integrate" use="optional">
			<xs:simpleType>
				<xs:restriction base="xs:NMTOKEN">
					<xs:enumeration value="replace"/>
					<xs:enumeration value="add"/>
				</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:annotation>
		<xs:documentation xml:lang="en">Use the category element to group rules/rulegroups.</xs:documentation>
		<xs:documentation xml:lang="en">The attribute name shows the category use, e.g. 'Grammar', 'Spelling', 'Style' etc.</xs:documentation>
	</xs:annotation>

	<xs:element name="category">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element ref="rule" />
				<xs:element ref="rulegroup" />
			</xs:choice>
			<xs:attribute name="default" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="off" />
						<xs:enumeration value="on" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute ref="name" use="required" />
			<xs:attribute name="id" type="xs:ID" use="required" />
			<xs:attribute ref="type" use="optional" />
			<xs:attribute name="external" type="binaryYesNo" use="optional" />
			<xs:attribute name="tab" use="optional" />
			<xs:attribute name="tags" use="optional" />
		</xs:complexType>
	</xs:element>

	<xs:annotation>
		<xs:documentation xml:lang="en"> Defines a group of rules
			to display several rules as one in the configuration user interface. A group has a unique ID.
			The whole rule group can be switched by default off using the attribute 'default'.</xs:documentation>
	</xs:annotation>
	<xs:element name="rulegroup">
		<xs:complexType>
			<xs:sequence minOccurs="1">
				<xs:element ref="url" minOccurs="0" maxOccurs="1" />
				<xs:element ref="short" minOccurs="0" maxOccurs="1" />
				<xs:element ref="antipattern" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="rule" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="default" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="off" />
						<xs:enumeration value="temp_off" />
						<xs:enumeration value="on" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute ref="name" use="required" />
			<xs:attribute name="id" type="xs:ID" use="required" />
			<xs:attribute ref="type" use="optional" />
			<xs:attribute name="tags" use="optional" />
		</xs:complexType>
	</xs:element>

	<xs:attribute name="type">
		<xs:annotation>
			<xs:documentation xml:lang="en">
				Localization Quality Issue Type, according to Internationalization Tag Set (ITS) Version 2.0,
				see http://www.w3.org/International/multilingualweb/lt/drafts/its20/its20.html#lqissue-typevalues
				(added in LanguageTool 2.0)
			</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:NMTOKEN">
				<xs:enumeration value="terminology" />
				<xs:enumeration value="mistranslation" />
				<xs:enumeration value="omission" />
				<xs:enumeration value="untranslated" />
				<xs:enumeration value="addition" />
				<xs:enumeration value="duplication" />
				<xs:enumeration value="inconsistency" />
				<xs:enumeration value="grammar" />
				<xs:enumeration value="legal" />
				<xs:enumeration value="register" />
				<xs:enumeration value="locale-specific-content" />
				<xs:enumeration value="locale-violation" />
				<xs:enumeration value="style" />
				<xs:enumeration value="characters" />
				<xs:enumeration value="misspelling" />
				<xs:enumeration value="typographical" />
				<xs:enumeration value="formatting" />
				<xs:enumeration value="inconsistent-entities" />
				<xs:enumeration value="numbers" />
				<xs:enumeration value="markup" />
				<xs:enumeration value="pattern-problem" />
				<xs:enumeration value="whitespace" />
				<xs:enumeration value="internationalization" />
				<xs:enumeration value="length" />
				<xs:enumeration value="non-conformance" />
				<xs:enumeration value="uncategorized" />
				<xs:enumeration value="other" />
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>

	<xs:annotation>
		<xs:documentation xml:lang="en"> The rule element. The
			unique ID is required only if the rule is not contained in a rule group.
			The rule can be switched by default off (using the default attribute).
		</xs:documentation>
	</xs:annotation>
	<xs:element name="rule">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="antipattern" minOccurs="0" maxOccurs="unbounded"/>
				<xs:choice>
					<xs:element ref="pattern" />
					<xs:element ref="regexp" />
				</xs:choice>
				<xs:element ref="filter" minOccurs="0" maxOccurs="1" />
				<xs:element ref="message" />
				<xs:element ref="suggestion" minOccurs="0" maxOccurs="15" />
				<xs:element ref="url" minOccurs="0" maxOccurs="1" />
				<xs:element ref="short" minOccurs="0" />
				<xs:element ref="example" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="default" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="off" />
						<xs:enumeration value="temp_off" />
						<xs:enumeration value="on" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="name" type="xs:string" use="optional" />
			<xs:attribute name="id" type="xs:ID" use="optional" />
			<xs:attribute ref="type" use="optional" />
			<xs:attribute name="tags" use="optional" />
		</xs:complexType>
	</xs:element>

 	<xs:element name="pattern">
		<xs:complexType>
			<xs:choice minOccurs="1" maxOccurs="unbounded">
				<xs:element ref="token" />
				<xs:element ref="phraseref" />
				<xs:element ref="and" />
				<xs:element ref="or" />
				<xs:element ref="unify" />
				<xs:element ref="marker" maxOccurs="1"/>
			</xs:choice>
			<xs:attribute name="case_sensitive" type="binaryYesNo" use="optional" />
			<xs:attribute name="raw_pos" type="binaryYesNo" use="optional" />
		</xs:complexType>
	</xs:element>

	<xs:element name="regexp">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="case_sensitive" type="binaryYesNo" use="optional"/>
                    <xs:attribute name="type" use="optional" default="smart">
                        <xs:simpleType>
                            <xs:restriction base="xs:NMTOKEN">
                                <xs:enumeration value="smart" />
                                <xs:enumeration value="exact" />
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                    <xs:attribute name="mark" use="optional">
                        <xs:simpleType>
							<xs:restriction base="xs:integer">
								<xs:minInclusive value="1" />
							</xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:annotation>
		<xs:documentation xml:lang="en">A negative-matching pattern used to
			mark up complex exceptions in rules. Note: it does not support
			phrases and OR operations for simplicity.
		</xs:documentation>
	</xs:annotation>
	<xs:element name="antipattern">
		<xs:complexType>
			<xs:choice minOccurs="1" maxOccurs="unbounded">
				<xs:element ref="token" />
				<xs:element ref="and" />
				<xs:element ref="unify" />
				<xs:element ref="marker" />
			</xs:choice>
			<xs:attribute name="case_sensitive" type="binaryYesNo" use="optional" />
		</xs:complexType>
	</xs:element>

	<xs:annotation>
		<xs:documentation xml:lang="en">A short description of
			the error detected by this rule displayed on the
			context menu in LibreOffice/OpenOffice.org.</xs:documentation>
	</xs:annotation>
	<xs:element name="short" type="xs:token" />


	<xs:annotation>
		<xs:documentation xml:lang="en">Message shown to the user if a rule matches.</xs:documentation>
	</xs:annotation>
	<xs:element name="message" xml:space="preserve">
		<xs:complexType mixed="true">
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="suggestion" />
				<xs:element ref="match" />
			</xs:choice>
		    <xs:attribute name="suppress_misspelled" type="binaryYesNo" use="optional"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="filter">
		<xs:complexType>
			<xs:attribute name="class" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation xml:lang="en">A fully qualified Java class that extends the RuleFilter class</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="args" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation xml:lang="en">Arguments given to the Java code: a space-separated list with 
						elements in the form of 'key:\x', where key is the parameter name and x is a number
						that refers to the pattern's token. Number and parameter names depend on the Java code.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:annotation>
			<xs:documentation xml:lang="en">URL with further information
				about the linguistic rule behind this error.</xs:documentation>
  	</xs:annotation>
	<xs:element name="url" type="xs:anyURI" />

	<xs:annotation>
		<xs:documentation xml:lang="en">Suggestion displayed to the user.</xs:documentation>
	</xs:annotation>
	<xs:element name="suggestion">
		<xs:complexType mixed="true">
			<xs:sequence minOccurs='0' maxOccurs='unbounded'>
				<xs:element ref="match" />
			</xs:sequence>
			<xs:attribute name="suppress_misspelled" type="binaryYesNo" use="optional"/>
		</xs:complexType>
	</xs:element>

	<xs:annotation>
		<xs:documentation xml:lang="en">Specifies examples used
			in JUnit tests and as documentation.
			The attribute 'correction' is used to check if the suggested correction
			is correct; multiple suggestions are joined with "|".
			The attribute triggers_error is not used by the software.
		</xs:documentation>
	</xs:annotation>

	<xs:element name="example" xml:space="preserve">
	<xs:complexType mixed="true">
	  <xs:choice minOccurs="0" maxOccurs="unbounded">
		<xs:element name="marker" >
			<xs:complexType>
				<xs:simpleContent>
					<xs:extension base="xs:string"/>
				</xs:simpleContent>
			</xs:complexType>
		</xs:element>
	  </xs:choice>
	  <xs:attribute name="correction" type="xs:string" use="optional" />
		<xs:attribute name="type" use="optional">
		<xs:simpleType>
		  <xs:restriction base="xs:NMTOKEN">
			<xs:enumeration value="correct" />
			<xs:enumeration value="incorrect" />
			<xs:enumeration value="triggers_error" />
		  </xs:restriction>
		</xs:simpleType>
		</xs:attribute>
	<xs:attribute name="reason" type="xs:string" use="optional" />
	</xs:complexType>
  </xs:element>

    <xs:attribute name="name">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:minLength value="1"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>

</xs:schema>

=== languagetool-org/languagetool/languagetool-language-modules/ca/src/main/resources/org/languagetool/rules/ca/ca-ES-valencia/grammar.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="../../../../../../../../../languagetool-core/src/main/resources/org/languagetool/rules/print.xsl" title="Pretty print" ?>
<?xml-stylesheet type="text/css" href="../../../../../../../../../languagetool-core/src/main/resources/org/languagetool/rules/rules.css" title="Easy editing stylesheet" ?>
<rules lang="ca-ES-valencia" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../../../../languagetool-core/src/main/resources/org/languagetool/rules/rules.xsd">
    <category id="VALENCIAN_RULES" name="Regles específiques per al diccionari valencià" type="grammar">
        <rule id="AMANEIXER" name="amanèixer (sinònim d'aparèixer)"> <!--només va amb el dicionari DNV-->
            <pattern>
                <token inflected="yes">amanèixer<exception inflected="yes">amanir</exception></token>
            </pattern>
            <message>Només és correcte en el sentit de 'aparèixer' (DNV). Per a altres sentits useu altres expressions.</message>
            <suggestion>(apuntar el dia)</suggestion>
            <suggestion>(fer-se clar)</suggestion>
            <suggestion>(fer-se de dia)</suggestion>
            <suggestion>(clarejar)</suggestion>
            <suggestion>(despertar-se)</suggestion>
            <suggestion>(a trenc d'alba)</suggestion>
            <example correction="(apuntar el dia)|(fer-se clar)|(fer-se de dia)|(clarejar)|(despertar-se)|(a trenc d'alba)">Aquell dia <marker>amaneixia</marker> amb fred.</example>
            <example>Amaneix bé l'ensalada.</example>
        </rule>
    </category>
</rules>

=== languagetool-org/languagetool/languagetool-core/src/test/resources/org/languagetool/rules/xx/style.xml
<?xml-stylesheet type="text/xsl" href="../print.xsl"
        title="Pretty print" ?>
<?xml-stylesheet type="text/css" href="../rules.css"
        title="Easy editing stylesheet" ?>
<!--
  ~ LanguageTool, a natural language style checker 
  ~ Copyright (c) 2023.  Stefan Viol (https://stevio.de)
  ~  
  ~  This library is free software; you can redistribute it and/or
  ~  modify it under the terms of the GNU Lesser General Public
  ~  License as published by the Free Software Foundation; either
  ~  version 2.1 of the License, or (at your option) any later version.
  ~  
  ~  This library is distributed in the hope that it will be useful,
  ~  but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
  ~  Lesser General Public License for more details.
  ~  
  ~  You should have received a copy of the GNU Lesser General Public
  ~  License along with this library; if not, write to the Free Software
  ~  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301
  ~  USA
  -->

<rules lang="xx" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../main/resources/org/languagetool/rules/rules.xsd">

    <category id="TONE_TAGE_TEST_STYLE_CATEGORY" name="TONE_TAGE_TEST_STYLE_CATEGORY">
        <rulegroup id="NO_TONE_TAG_GROUP" name="NO_TONE_TAG_GROUP">
            <rule id="Formal_Clarity_TONE_RULE" tone_tags="formal clarity">
                <pattern>
                    <token>Formal-Clarity-Match</token>
                </pattern>
                <message>Do you mean <suggestion>Formal-Clarity-Match-Fixed</suggestion></message>
                <example correction="Formal-Clarity-Match-Fixed">This is an example for a <marker>Formal-Clarity-Match</marker>.</example>
                <example>This is an example for a Formal-Clarity-Match-Fixed.</example>
            </rule>
            <rule id="NO_TONE_RULE">
                <pattern>
                    <token>No-Tone-Needed-Match</token>
                </pattern>
                <message>Do you mean <suggestion>No-Tone-Needed-Match-Fixed</suggestion>?</message>
                <example correction="No-Tone-Needed-Match-Fixed">This is an example for a <marker>No-Tone-Needed-Match</marker>.</example>
                <example>This is an example for a No-Tone-Needed-Match-Fixed.</example>
            </rule>
        </rulegroup>
        <rulegroup id="TONE_TAG_GROUP" name="TONE_TAG_GROUP" tone_tags="confident academic">
            <rule id="CONFIDENT_ACADEMIC_SCIENTIFIC_TONE_RULE" tone_tags="confident scientific">
                <pattern>
                    <token>Confident-Academic-Scientific-Match</token>
                </pattern>
                <message>Do you mean <suggestion>Confident-Academic-Scientific-Match-Fixed</suggestion>?</message>
                <example correction="Confident-Academic-Scientific-Match-Fixed">This is an example for a <marker>Confident-Academic-Scientific-Match</marker>.</example>
                <example>This is an example for a Confident-Academic-Scientific-Match-Fixed</example>
            </rule>
            <rule id="CONFIDENT_ACADEMIC_TONE_RULE">
                <pattern>
                    <token>Confident-Academic-Match</token>
                </pattern>
                <message>Do you mean <suggestion>Confident-Academic-Match-Fixed</suggestion>?</message>
                <example correction="Confident-Academic-Match-Fixed">This is an example for a <marker>Confident-Academic-Match</marker>.</example>
                <example>This is an example for a Confident-Academic-Match-Fixed</example>
            </rule>
        </rulegroup>
        <rulegroup id="PICKY_TONE_TAG_GROUP" name="PICKY_TONE_TAG_GROUP" tags="picky" tone_tags="clarity confident academic">
            <rule id="PICKY-CLARITY_CONFIDENT_ACADEMIC_TONE_RULE">
                <pattern>
                    <token>Picky-Clarity-Confident-Academic-Match</token>
                </pattern>
                <message>Do you mean <suggestion>Picky-Clarity-Confident-Academic-Match-Fixed</suggestion>?</message>
                <example correction="Picky-Clarity-Confident-Academic-Match-Fixed">This is an example for a <marker>Picky-Clarity-Confident-Academic-Match</marker>.</example>
                <example>this is an example for a Picky-Clarity-Confident-Academic-Match-Fixed</example>
            </rule>
            <rule id="PICKY-CLARITY_CONFIDENT_ACADEMIC_SCIENTIFIC_TONE_RULE" tone_tags="scientific">
                <pattern>
                    <token>Picky-Clarity-Confident-Academic-Scientific-Match</token>
                </pattern>
                <message>Do you mean <suggestion>Picky-Clarity-Confident-Academic-Scientific-Match-Fixed</suggestion>?</message>
                <example correction="Picky-Clarity-Confident-Academic-Scientific-Match-Fixed">This is an example for a <marker>Picky-Clarity-Confident-Academic-Scientific-Match</marker>.</example>
                <example>this is an example for a Picky-Clarity-Confident-Academic-Scientific-Match-Fixed</example>
            </rule>
        </rulegroup>
    </category>
    <category name="TONE_TAGE_TEST_STYLE_CATEGORY_CAT_TAGGED" id="TONE_TAGE_TEST_STYLE_CATEGORY_CAT_TAGGED" tone_tags="persuasive objective">
        <rule id="PERSUASIVE_OBJECTIVE_TONE_RULE" name="PERSUASIVE_OBJECTIVE_TONE_RULE">
                <pattern>
                    <token>Persuasive-Objective-Match</token>
                </pattern>
                <message>Do you mean <suggestion>Persuasive-Objective-Match-Fixed</suggestion>?</message>
                <example correction="Persuasive-Objective-Match-Fixed">This is an example for a <marker>Persuasive-Objective-Match</marker>.</example>
                <example>This is an example for a Persuasive-Objective-Match-Fixed.</example>
        </rule>
        <rule id="PERSUASIVE_OBJECTIVE_INFORMAL_TONE_RULE" name="PERSUASIVE_OBJECTIVE_INFORMAL_TONE_RULE" tone_tags="informal">
                <pattern>
                    <token>Persuasive-Objective-Informal-Match</token>
                </pattern>
                <message>Do you mean <suggestion>Persuasive-Objective-Informal-Match-Fixed</suggestion>?</message>
                <example correction="Persuasive-Objective-Informal-Match-Fixed">This is an example for a <marker>Persuasive-Objective-Informal-Match</marker>.</example>
                <example>This is an example for a Persuasive-Objective-Match-Informal-Fixed.</example>
        </rule>
    </category>
    <category name="IS_GOAL_SPECIFIC_CATEGORY_TEST" id="IS_GOAL_SPECIFIC_CATEGORY_TEST">
        <rule id="PERSUASIVE_GOAL_SPECIFIC_TONE_RULE" name="PERSUASIVE_GOAL_SPECIFIC_TONE_RULE" is_goal_specific="true" tone_tags="persuasive">
                <pattern>
                    <token>Persuasive-Goal-Specific-Match</token>
                </pattern>
                <message>Do you mean <suggestion>Persuasive-Goal-Specific-Match-Fixed</suggestion>?</message>
                <example correction="Persuasive-Goal-Specific-Match-Fixed">This is an example for a <marker>Persuasive-Goal-Specific-Match</marker>.</example>
                <example>This is an example for a Persuasive-Goal-Specific-Match-Fixed.</example>
        </rule>
        <rule id="PERSUASIVE_NOT_GOAL_SPECIFIC_TONE_RULE" name="PERSUASIVE_NOT_GOAL_SPECIFIC_TONE_RULE" tone_tags="persuasive">
                <pattern>
                    <token>Persuasive-Not-Goal-Specific-Match</token>
                </pattern>
                <message>Do you mean <suggestion>Persuasive-Not-Goal-Specific-Match-Fixed</suggestion>?</message>
                <example correction="Persuasive-Not-Goal-Specific-Match-Fixed">This is an example for a <marker>Persuasive-Not-Goal-Specific-Match</marker>.</example>
                <example>This is an example for a Persuasive-Not-Goal-Specific-Match-Fixed.</example>
        </rule>
    </category>
</rules>

=== languagetool-org/languagetool/languagetool-language-modules/lv/src/main/resources/org/languagetool/rules/lv/grammar.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="../../../../../../../../../languagetool-core/src/main/resources/org/languagetool/rules/print.xsl" title="Pretty print"?>
<?xml-stylesheet type="text/css" href="../../../../../../../../../languagetool-core/src/main/resources/org/languagetool/rules/rules.css" title="Easy editing stylesheet"?>
<!--
LanguageTool Grammar rules for Latvian language
Copyright (C) 2006 Mantas Kriaučiūnas (www.openoffice.lv ; mantas@akl.lv)

Should follow rules, described in in government resolution number 60:
http://www3.lrs.lv/pls/inter3/dokpaieska.showdoc_l?p_id=41265
Don't forget to check this and next resolutions against these rules ! 
Partially based on Polish grammar rules, copyright (C) 2006 Marcin Miłkowski

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
-->

<!-- Unless otherwise stated, citations refer to ANDRA KALNAČA, ILZE LOKMANE - LATVIAN GRAMMAR -->
<rules lang="lv" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../../../../languagetool-core/src/main/resources/org/languagetool/rules/rules.xsd">
	<category id="CAT1" name="Šķiršanās kļūdas">
		<rulegroup id="prepositions" name="Prepositions">
			<!-- Page 330 Section 2.7.2 -->
			<rule name="accusative">
				<pattern>
					<marker>
						<token regexp="yes">ap|caur|gar|pār</token>
						<token postag="N[^A]...." postag_regexp="yes" />
					</marker>
				</pattern>
				<message>\1 [ko]</message>
				<suggestion>\1 draugu</suggestion>
				<example correction="ap draugu">
					<marker>ap draugs</marker>
				</example>
			</rule>
			<rule name="instrumental">
				<pattern>
					<marker>
						<token regexp="yes">ar</token>
						<token postag="N[^A]S...|N[^D]P..." postag_regexp="yes" />
					</marker>
				</pattern>
				<message>\1 [ko]</message>
				<suggestion>\1 draugiem</suggestion>
				<example correction="ar draugiem">
					<marker>ar draugus</marker>
				</example>
			</rule>
			<rule name="genitive">
				<pattern>
					<marker>
						<token regexp="yes">bez|no</token>
						<token postag="N[^G]...." postag_regexp="yes" />
					</marker>
				</pattern>
				<message>\1 [ko]</message>
				<suggestion>\1 drauga</suggestion>
				<example correction="no drauga">
					<marker>no draugs</marker>
				</example>
			</rule>
		</rulegroup>
	</category>

</rules>
