=== languagetool-org/languagetool/languagetool-core/src/main/resources/org/languagetool/rules/rules.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<!-- 
 * LanguageTool, a natural language style checker 
 * Copyright (c) Marcin MiÅ‚kowski, 2014 (http://www.languagetool.org)
 * 
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301
 * USA
 
 Schema for rule files
 -->

	<xs:include schemaLocation="pattern.xsd"/>

	<xs:annotation>
		<xs:documentation xml:lang="en">Main element</xs:documentation>
	</xs:annotation>

	<xs:element name="rules">
		<xs:complexType>
			<xs:choice minOccurs="1" maxOccurs="unbounded" >
				<xs:element ref="unification" />
				<xs:element ref="phrases"/>
				<xs:element ref="category"/>
			</xs:choice>
			<xs:attribute name="lang" type="xs:language" use="required" />
			<xs:attribute name="idprefix" type="xs:string" use="optional" />
			<xs:attribute name="integrate" use="optional">
			<xs:simpleType>
				<xs:restriction base="xs:NMTOKEN">
					<xs:enumeration value="replace"/>
					<xs:enumeration value="add"/>
				</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:annotation>
		<xs:documentation xml:lang="en">Use the category element to group rules/rulegroups.</xs:documentation>
		<xs:documentation xml:lang="en">The attribute name shows the category use, e.g. 'Grammar', 'Spelling', 'Style' etc.</xs:documentation>
	</xs:annotation>

	<xs:element name="category">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element ref="rule" />
				<xs:element ref="rulegroup" />
			</xs:choice>
			<xs:attribute name="default" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="off" />
						<xs:enumeration value="on" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute ref="name" use="required" />
			<xs:attribute name="id" type="xs:ID" use="required" />
			<xs:attribute ref="type" use="optional" />
			<xs:attribute name="external" type="binaryYesNo" use="optional" />
			<xs:attribute name="tab" use="optional" />
			<xs:attribute name="tags" use="optional" />
		</xs:complexType>
	</xs:element>

	<xs:annotation>
		<xs:documentation xml:lang="en"> Defines a group of rules
			to display several rules as one in the configuration user interface. A group has a unique ID.
			The whole rule group can be switched by default off using the attribute 'default'.</xs:documentation>
	</xs:annotation>
	<xs:element name="rulegroup">
		<xs:complexType>
			<xs:sequence minOccurs="1">
				<xs:element ref="url" minOccurs="0" maxOccurs="1" />
				<xs:element ref="short" minOccurs="0" maxOccurs="1" />
				<xs:element ref="antipattern" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="rule" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="default" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="off" />
						<xs:enumeration value="temp_off" />
						<xs:enumeration value="on" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute ref="name" use="required" />
			<xs:attribute name="id" type="xs:ID" use="required" />
			<xs:attribute ref="type" use="optional" />
			<xs:attribute name="tags" use="optional" />
		</xs:complexType>
	</xs:element>

	<xs:attribute name="type">
		<xs:annotation>
			<xs:documentation xml:lang="en">
				Localization Quality Issue Type, according to Internationalization Tag Set (ITS) Version 2.0,
				see http://www.w3.org/International/multilingualweb/lt/drafts/its20/its20.html#lqissue-typevalues
				(added in LanguageTool 2.0)
			</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:NMTOKEN">
				<xs:enumeration value="terminology" />
				<xs:enumeration value="mistranslation" />
				<xs:enumeration value="omission" />
				<xs:enumeration value="untranslated" />
				<xs:enumeration value="addition" />
				<xs:enumeration value="duplication" />
				<xs:enumeration value="inconsistency" />
				<xs:enumeration value="grammar" />
				<xs:enumeration value="legal" />
				<xs:enumeration value="register" />
				<xs:enumeration value="locale-specific-content" />
				<xs:enumeration value="locale-violation" />
				<xs:enumeration value="style" />
				<xs:enumeration value="characters" />
				<xs:enumeration value="misspelling" />
				<xs:enumeration value="typographical" />
				<xs:enumeration value="formatting" />
				<xs:enumeration value="inconsistent-entities" />
				<xs:enumeration value="numbers" />
				<xs:enumeration value="markup" />
				<xs:enumeration value="pattern-problem" />
				<xs:enumeration value="whitespace" />
				<xs:enumeration value="internationalization" />
				<xs:enumeration value="length" />
				<xs:enumeration value="non-conformance" />
				<xs:enumeration value="uncategorized" />
				<xs:enumeration value="other" />
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>

	<xs:annotation>
		<xs:documentation xml:lang="en"> The rule element. The
			unique ID is required only if the rule is not contained in a rule group.
			The rule can be switched by default off (using the default attribute).
		</xs:documentation>
	</xs:annotation>
	<xs:element name="rule">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="antipattern" minOccurs="0" maxOccurs="unbounded"/>
				<xs:choice>
					<xs:element ref="pattern" />
					<xs:element ref="regexp" />
				</xs:choice>
				<xs:element ref="filter" minOccurs="0" maxOccurs="1" />
				<xs:element ref="message" />
				<xs:element ref="suggestion" minOccurs="0" maxOccurs="15" />
				<xs:element ref="url" minOccurs="0" maxOccurs="1" />
				<xs:element ref="short" minOccurs="0" />
				<xs:element ref="example" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="default" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="off" />
						<xs:enumeration value="temp_off" />
						<xs:enumeration value="on" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="name" type="xs:string" use="optional" />
			<xs:attribute name="id" type="xs:ID" use="optional" />
			<xs:attribute ref="type" use="optional" />
			<xs:attribute name="tags" use="optional" />
		</xs:complexType>
	</xs:element>

 	<xs:element name="pattern">
		<xs:complexType>
			<xs:choice minOccurs="1" maxOccurs="unbounded">
				<xs:element ref="token" />
				<xs:element ref="phraseref" />
				<xs:element ref="and" />
				<xs:element ref="or" />
				<xs:element ref="unify" />
				<xs:element ref="marker" maxOccurs="1"/>
			</xs:choice>
			<xs:attribute name="case_sensitive" type="binaryYesNo" use="optional" />
			<xs:attribute name="raw_pos" type="binaryYesNo" use="optional" />
		</xs:complexType>
	</xs:element>

	<xs:element name="regexp">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="case_sensitive" type="binaryYesNo" use="optional"/>
                    <xs:attribute name="type" use="optional" default="smart">
                        <xs:simpleType>
                            <xs:restriction base="xs:NMTOKEN">
                                <xs:enumeration value="smart" />
                                <xs:enumeration value="exact" />
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                    <xs:attribute name="mark" use="optional">
                        <xs:simpleType>
							<xs:restriction base="xs:integer">
								<xs:minInclusive value="1" />
							</xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:annotation>
		<xs:documentation xml:lang="en">A negative-matching pattern used to
			mark up complex exceptions in rules. Note: it does not support
			phrases and OR operations for simplicity.
		</xs:documentation>
	</xs:annotation>
	<xs:element name="antipattern">
		<xs:complexType>
			<xs:choice minOccurs="1" maxOccurs="unbounded">
				<xs:element ref="token" />
				<xs:element ref="and" />
				<xs:element ref="unify" />
				<xs:element ref="marker" />
			</xs:choice>
			<xs:attribute name="case_sensitive" type="binaryYesNo" use="optional" />
		</xs:complexType>
	</xs:element>

	<xs:annotation>
		<xs:documentation xml:lang="en">A short description of
			the error detected by this rule displayed on the
			context menu in LibreOffice/OpenOffice.org.</xs:documentation>
	</xs:annotation>
	<xs:element name="short" type="xs:token" />


	<xs:annotation>
		<xs:documentation xml:lang="en">Message shown to the user if a rule matches.</xs:documentation>
	</xs:annotation>
	<xs:element name="message" xml:space="preserve">
		<xs:complexType mixed="true">
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="suggestion" />
				<xs:element ref="match" />
			</xs:choice>
		    <xs:attribute name="suppress_misspelled" type="binaryYesNo" use="optional"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="filter">
		<xs:complexType>
			<xs:attribute name="class" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation xml:lang="en">A fully qualified Java class that extends the RuleFilter class</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="args" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation xml:lang="en">Arguments given to the Java code: a space-separated list with 
						elements in the form of 'key:\x', where key is the parameter name and x is a number
						that refers to the pattern's token. Number and parameter names depend on the Java code.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:annotation>
			<xs:documentation xml:lang="en">URL with further information
				about the linguistic rule behind this error.</xs:documentation>
  	</xs:annotation>
	<xs:element name="url" type="xs:anyURI" />

	<xs:annotation>
		<xs:documentation xml:lang="en">Suggestion displayed to the user.</xs:documentation>
	</xs:annotation>
	<xs:element name="suggestion">
		<xs:complexType mixed="true">
			<xs:sequence minOccurs='0' maxOccurs='unbounded'>
				<xs:element ref="match" />
			</xs:sequence>
			<xs:attribute name="suppress_misspelled" type="binaryYesNo" use="optional"/>
		</xs:complexType>
	</xs:element>

	<xs:annotation>
		<xs:documentation xml:lang="en">Specifies examples used
			in JUnit tests and as documentation.
			The attribute 'correction' is used to check if the suggested correction
			is correct; multiple suggestions are joined with "|".
			The attribute triggers_error is not used by the software.
		</xs:documentation>
	</xs:annotation>

	<xs:element name="example" xml:space="preserve">
	<xs:complexType mixed="true">
	  <xs:choice minOccurs="0" maxOccurs="unbounded">
		<xs:element name="marker" >
			<xs:complexType>
				<xs:simpleContent>
					<xs:extension base="xs:string"/>
				</xs:simpleContent>
			</xs:complexType>
		</xs:element>
	  </xs:choice>
	  <xs:attribute name="correction" type="xs:string" use="optional" />
		<xs:attribute name="type" use="optional">
		<xs:simpleType>
		  <xs:restriction base="xs:NMTOKEN">
			<xs:enumeration value="correct" />
			<xs:enumeration value="incorrect" />
			<xs:enumeration value="triggers_error" />
		  </xs:restriction>
		</xs:simpleType>
		</xs:attribute>
	<xs:attribute name="reason" type="xs:string" use="optional" />
	</xs:complexType>
  </xs:element>

    <xs:attribute name="name">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:minLength value="1"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>

</xs:schema>

=== languagetool-org/languagetool/languagetool-language-modules/nl/src/main/resources/org/languagetool/rules/nl/nl-BE/style.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../../../../../../../../../languagetool-core/src/main/resources/org/languagetool/rules/print.xsl" title="Pretty print" ?>
<?xml-stylesheet type="text/css" href="../../../../../../../../../languagetool-core/src/main/resources/org/languagetool/rules/rules.css" title="Easy editing stylesheet" ?>
<!--
Dutch Style Rules for LanguageTool
See tagset.txt for the meaning of the POS tags
Copyright (C) 2001-2023 Daniel Naber (http://www.danielnaber.de),
  Marcin Miłkowski, and the LanguageTool contributors
This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.
This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301
USA
-->
<rules lang="nl" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/languagetool-org/languagetool/master/languagetool-core/src/main/resources/org/languagetool/rules/rules.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <category id="STYLE_NLBE" name="style rules" type="style" default="off">
        <rule id="TEMP_RULE_NLBE" name="temp rule">
            <pattern>
                <token>Belgie</token>
            </pattern>
            <message>Test rule.</message>
            <suggestion>België</suggestion>
            <example correction="België"><marker>Belgie</marker></example>
        </rule>
    </category>
</rules>

=== languagetool-org/languagetool/languagetool-language-modules/pt/src/main/resources/org/languagetool/rules/pt/pt-BR/style.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../../../../../../../../../languagetool-core/src/main/resources/org/languagetool/rules/print.xsl" title="Pretty print" ?>
<?xml-stylesheet type="text/css" href="../../../../../../../../../languagetool-core/src/main/resources/org/languagetool/rules/rules.css" title="Easy editing stylesheet" ?>
<!--
 LanguageTool Premium Error Detection Rules - Style
 Copyright (C) 2023  LanguageTooler GmbH
 All rights reserved - not part of the Open Source edition
-->
<rules premium="yes" lang="pt" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/languagetool-org/languagetool/master/languagetool-core/src/main/resources/org/languagetool/rules/rules.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <category id="STYLE" name="style rules" type="style">
        <rule id="REMOVEME_RULE3" name="test rule" default="off">
            <pattern>
                <token>realizaaar</token>
            </pattern>
            <message>Test rule.</message>
            <suggestion>realizar</suggestion>
            <example correction="realizar"><marker>realizaaar</marker></example>
        </rule>
    </category>
</rules>

=== languagetool-org/languagetool/trunk/JLanguageTool/src/rules/en/en-GB/grammar.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../print.xsl" ?>
<?xml-stylesheet type="text/css" href="../rules.css"
title="Easy editing stylesheet" ?>
<!--
British English Grammar and Typo Rules for LanguageTool
See tagset.txt for the meaning of the POS tags
Copyright (C) 2012 Marcin Miłkowski (http://www.languagetool.org)

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301
USA

$Id: grammar.xml 7145 2012-06-01 10:52:39Z milek_pl $
-->
<!--suppress CheckTagEmptyBody -->
<rules lang="en" xsi:noNamespaceSchemaLocation="../rules.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<!-- ====================================================================== -->
	<!-- Possible typos -->
	<!-- ====================================================================== -->
	<category name="American English phrases">
		<rule id="ZIP_CODE_POSTCODE" name="zip code/postcode">
			<pattern>
				<token>zip</token>
				<token>code</token>
			</pattern>
			<message>
				This expression is common for American English. Did you mean <suggestion>postcode</suggestion>?
			</message>
			<url>http://www.learnenglish.de/mistakes/USvsBrEnglish.html</url>
			<example type="incorrect">Please enter your <marker>zip code</marker>.</example>
			<example type="correct">Please enter your postcode.</example>
		</rule>
		<rule id="APARTMENT-FLAT" name="apartment/flat">
			<pattern>
				<token>apartment</token>				
			</pattern>
			<message>
				This word is common for American English. Did you mean <suggestion>flat</suggestion>?
			</message>
			<url>http://www.learnenglish.de/mistakes/USvsBrEnglish.html</url>
			<example type="incorrect">I just bought an <marker>apartment</marker>?</example>
			<example type="correct">Where's your flat?</example>
		</rule>
		<rule id="BAND-AID_PLASTER" name="band-aid/plaster">
			<pattern>
				<token>band-aid</token>				
			</pattern>
			<message>
				This word is common for American English. Did you mean <suggestion>plaster</suggestion>?
			</message>
			<url>http://www.learnenglish.de/mistakes/USvsBrEnglish.html</url>
			<example type="incorrect">Where's the <marker>band-aid</marker>?</example>
			<example type="correct">Where's the plaster?</example>
		</rule>
		<rule id="GROUND_VS_MINCED" name="ground beef/minced beef">
			<pattern>
				<marker>
				<token>ground</token>
				</marker>
				<token>beef</token>				
			</pattern>
			<message>
				This word is common for American English. Did you mean <suggestion>minced</suggestion>?
			</message>
			<url>http://www.learnenglish.de/mistakes/USvsBrEnglish.html</url>
			<example type="incorrect">Do vegetarians eat <marker>ground</marker> beef?</example>
			<example type="correct">No, vegetarians do not eat minced beef.</example>
		</rule>
		<rule id="FIRST_GROUND_FLOOR" name="first floor/ground floor">
			<pattern>
				<marker>
				<token>first</token>
				</marker>
				<token>floor</token>				
			</pattern>
			<message>
				This word is common for American English. Did you mean <suggestion>ground</suggestion>?
			</message>
			<url>http://www.learnenglish.de/mistakes/USvsBrEnglish.html</url>
			<example type="incorrect">The room is on the <marker>first</marker> floor.</example>
			<example type="correct">You mean on the ground floor?</example>
		</rule>
		<rule id="VACUUM_CLEANER_HOOVER" name="vacuum cleaner/hoover">
			<pattern>
				<marker>
				<token>vacuum</token>				
				<token inflected="yes">cleaner</token>
				</marker>				
			</pattern>
			<message>
				This expression is common for American English. Did you mean <suggestion>hoover</suggestion>?
			</message>
			<url>http://www.learnenglish.de/mistakes/USvsBrEnglish.html</url>
			<example type="incorrect">Buy me a <marker>vacuum cleaner</marker>.</example>
			<example type="correct">All I need is a hoover.</example>
		</rule>
		<rule id="MOVIE_THEATER_CINEMA" name="movie theater/cinema">
			<pattern>
				<marker>
				<token>movie</token>				
				<token inflected="yes">theater</token>
				</marker>				
			</pattern>
			<message>
				This expression is common for American English. Did you mean <suggestion>cinema</suggestion>?
			</message>
			<url>http://www.learnenglish.de/mistakes/USvsBrEnglish.html</url>
			<example type="incorrect">Let's go to a <marker>movie theater</marker>.</example>
			<example type="correct">Edward Norton – not appearing in a cinema near you.</example>
		</rule>		
		<rule id="GOT_GOTTEN" name="gotten/got">
			<pattern>
				<marker><token>gotten</token></marker>
				<token><exception>up</exception></token>
			</pattern>
			<message>In the UK, the word 'gotten' is usually no longer used. Did you mean <suggestion>got</suggestion>?</message>
			<url>http://public.wsu.edu/~brians/errors/got.html</url>
			<example type="correct">He's gotten up on the wrong side of bed.</example>
			<example type="incorrect" correction="got">He has <marker>gotten</marker> some food.</example>
		</rule>
				
	</category>
</rules>

=== languagetool-org/languagetool/languagetool-core/src/test/resources/org/languagetool/rules/xx/grammar-nonPremium.xml
<?xml-stylesheet type="text/xsl" href="../print.xsl"
        title="Pretty print" ?>
<?xml-stylesheet type="text/css" href="../rules.css"
        title="Easy editing stylesheet" ?>
<!--
  ~ LanguageTool, a natural language style checker 
  ~ Copyright (c) 2023.  Stefan Viol (https://stevio.de)
  ~  
  ~  This library is free software; you can redistribute it and/or
  ~  modify it under the terms of the GNU Lesser General Public
  ~  License as published by the Free Software Foundation; either
  ~  version 2.1 of the License, or (at your option) any later version.
  ~  
  ~  This library is distributed in the hope that it will be useful,
  ~  but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
  ~  Lesser General Public License for more details.
  ~  
  ~  You should have received a copy of the GNU Lesser General Public
  ~  License along with this library; if not, write to the Free Software
  ~  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301
  ~  USA
  -->

<!-- 
    Tag:
    F = file
    C = category
    RG = ruleGroup
    R = rule
    Status:
    -NP = nonPremium
    -p = premium
    ID template category tag F-NP_C-NP (File-Status_Category-Status)
    ID template rulegroup tag F-NP_C-NP_RG-NP (File-Status_Category-Status_RuleGroup-Status)
    ID template rule F-NP_C-NP_RG-NP_R-NP (File-Status_Category-Status_RuleGroup-Status_Rule-Status)
-->
<rules lang="xx" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../main/resources/org/languagetool/rules/rules.xsd">
    <category id="F-NP_C-NP" name="F-NP_C-NP">
        <rulegroup id="F-NP_C-NP_RG-NP" name="F-NP_C-NP_RG-NP">
            <rule id="F-NP_C-NP_RG-NP_R-NP">
                <pattern>
                    <token>fake1</token>
                </pattern>
                <message>msg1</message>
                <example correction="">
                    <marker>fake1</marker>
                </example>
                <example>fake2</example>
            </rule>
            <rule id="F-NP_C-NP_RG-NP_R-P" premium="yes">
                <pattern>
                    <token>fake1</token>
                </pattern>
                <message>msg3</message>
                <example correction="">
                    <marker>fake1</marker>
                </example>
                <example>fake2</example>
            </rule>
        </rulegroup>
        <rulegroup id="F-NP_C-NP_RG-P" name="F-NP_C-NP_RG-P" premium="yes">
            <rule id="F-NP_C-NP_RG-P_R-NP" premium="no">
                <pattern>
                    <token>fake1</token>
                </pattern>
                <message>msg1</message>
                <example correction="">
                    <marker>fake1</marker>
                </example>
                <example>fake2</example>
            </rule>
            <rule id="F-NP_C-NP_RG-P_R-P">
                <pattern>
                    <token>fake1</token>
                </pattern>
                <message>msg3</message>
                <example correction="">
                    <marker>fake1</marker>
                </example>
                <example>fake2</example>
            </rule>
        </rulegroup>
    </category>
    <category id="F-NP_C-P" name="F-NP_C-P" premium="yes">
        <rulegroup id="F-NP_C-P_RG-NP" name="F-NP_C-P_RG-NP" premium="no">
            <rule id="F-NP_C-P_RG-NP_R-NP">
                <pattern>
                    <token>fake1</token>
                </pattern>
                <message>msg1</message>
                <example correction="">
                    <marker>fake1</marker>
                </example>
                <example>fake2</example>
            </rule>
            <rule id="F-NP_C-P_RG-NP_R-P">
                <pattern>
                    <token>fake1</token>
                </pattern>
                <message>msg3</message>
                <example correction="">
                    <marker>fake1</marker>
                </example>
                <example>fake2</example>
            </rule>
        </rulegroup>
        <rulegroup id="F-NP_C-P_RG-P" name="F-NP_C-P_RG-P">
            <rule id="F-NP_C-P_RG-P_R-NP" premium="no">
                <pattern>
                    <token>fake1</token>
                </pattern>
                <message>msg1</message>
                <example correction="">
                    <marker>fake1</marker>
                </example>
                <example>fake2</example>
            </rule>
            <rule id="F-NP_C-P_RG-P_R-P">
                <pattern>
                    <token>fake1</token>
                </pattern>
                <message>msg3</message>
                <example correction="">
                    <marker>fake1</marker>
                </example>
                <example>fake2</example>
            </rule>
        </rulegroup>
    </category>
</rules>
